name: PR CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-package:
    name: CI
    permissions:
      contents: read
      packages: write

    uses: high-effort-low-stress/workflows/.github/workflows/nextjs-build-test.yaml@main
    with:
      image-name: ghcr.io/${{ github.repository }}
      sha: ${{ github.sha }}
      node-version: '22'
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
